# disable test containers
quarkus.devservices.enabled=false


# jdbc:db-order//
quarkus.datasource.db-restaurant.db-kind=postgresql
quarkus.datasource.db-restaurant.username=guest
quarkus.datasource.db-restaurant.password=welcome1
quarkus.datasource.db-restaurant.jdbc.url=jdbc:postgresql://localhost:5432/postgres?escapeSyntaxCallMode=callIfNoReturn
#&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
quarkus.datasource.db-restaurant.jdbc.max-size=16
#quarkus.datasource.db-order.flush-on-close=true

# RestaurantInfo Camel SQL Expression
spEL.sym=$
restaurant.approval.topic.request=restaurant-approval-request
restaurant.approval.topic.response=restaurant-approval-response

restaurantInfo.camel.sql.spEL=sql:classpath:templates/findRestaurantsAndProductsInformation.sql
joinedProductIds.camel.spEL=joinedProductIds(${spEL.sym}{body.orderDetail.products})
sendOrderApprovalEvent.spEL=direct:saveOrderApproval,seda:orderApprovalEventMessage
#?outputType=StreamList&outputClass=com.food.ordering.system.order.service.application.service.dto.create.RestaurantProductsInfoDTO

#kafka:common:properties
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.schema-registry-u-r-l=http://localhost:8081

# kafka:producer:config:data:properties
camel.component.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
camel.component.kafka.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
camel.component.kafka.compression-codec=snappy
camel.component.kafka.request-required-acks=all
camel.component.kafka.producer-batch-size=16384
camel.component.kafka.linger-ms=5
camel.component.kafka.request-timeout-ms=6000
camel.component.kafka.retries=5

# kafka:consumer:config:data:properties
camel.component.kafka.groupId=restaurant-approval-topic-consumer
camel.component.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
camel.component.kafka.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.specific-avro-reader=true
#camel.component.kafka.batch-listener=true
camel.component.kafka.consumers-count=3

